In [1]:
import numpy as np

In [2]:
v = np.array([2, 1, 4, 3, 5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [4]:
np.sort(v) # yan etkisiz metoddur. bagimsiz

array([1, 2, 3, 4, 5])

In [5]:
v

array([2, 1, 4, 3, 5])

In [6]:
v.sort() # bu metod ise yan etkili metoddur

In [7]:
v

array([1, 2, 3, 4, 5])

In [8]:
# iki boyutlu array siralama

In [9]:
m = np.random.normal(20, 5, (3, 3))

In [10]:
m

array([[15.77872697, 16.02682975, 32.0418355 ],
       [18.941593  , 26.31408848, 18.15136632],
       [ 6.58205089, 17.08804747, 17.67323536]])

In [11]:
np.sort(m, axis=1) # her bir satiri kendi icinde siraladi

array([[15.77872697, 16.02682975, 32.0418355 ],
       [18.15136632, 18.941593  , 26.31408848],
       [ 6.58205089, 17.08804747, 17.67323536]])

In [13]:
np.sort(m, axis=0)

array([[ 6.58205089, 16.02682975, 17.67323536],
       [15.77872697, 17.08804747, 18.15136632],
       [18.941593  , 26.31408848, 32.0418355 ]])