In [1]:
import numpy as np

Öğrenilen Fonksiyonlar

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.full((3, 5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [5]:
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [6]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [7]:
np.random.normal(65, 2, (3, 4))

array([[63.50781363, 69.31530149, 63.81706272, 63.62595202],
       [64.28800861, 64.76754684, 62.75819421, 63.80941641],
       [65.39821854, 64.11221517, 65.07626886, 65.61224297]])

In [8]:
np.random.randint(0, 10, (3, 3))

array([[4, 1, 9],
       [8, 2, 6],
       [4, 7, 8]])

* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [9]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
x = np.array([1, 2, 4])
y = np.array([4, 5, 6])

In [11]:
np.concatenate([x, y])

array([1, 2, 4, 4, 5, 6])

* split
* vsplit
* hsplit

In [12]:
np.sort(x, axis=0)

array([1, 2, 4])

In [13]:
np.eye(3,3) # birim matris olusturmaya yariyor

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(3,5) # dikdortgen matris

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [15]:
np.random.randint(10, size=[3, 3, 2]) # 3 adet, 3 satir, 2 sutun seklinde yazilir

array([[[6, 3],
        [6, 3],
        [8, 8]],

       [[4, 6],
        [6, 7],
        [1, 5]],

       [[1, 1],
        [8, 6],
        [9, 2]]])

In [16]:
np.arange(1, 10) # 1'den 9'a kadar sayiları uretir (10 dahil degil)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
5*np.array([1, 2, 3])

array([ 5, 10, 15])