In [1]:
import numpy as np

In [2]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a = np.arange(1, 10)

In [5]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.ndim

1

In [7]:
b = a.reshape(1, 9) # 1 satirli 9 sutunlu bir matrise donusturduk. degismemis gibi gozukse de matrise donustugu icin boyutu 2'ye yukseldi

In [8]:
b.ndim

2

In [9]:
# yani tek boyuttan cok boyuta gectik ama tek boyutun bilgilerini koruduk