In [1]:
import numpy as np 

5*x0 + x1 = 12

x0 + 3*x1 = 10

In [2]:
a = np.array([[5, 1], [1, 3]]) # once bilinmeyen denklemlerin katsayilarini yaziyoruz (iki boyutlu)

In [3]:
a

array([[5, 1],
       [1, 3]])

In [4]:
b = np.array([12, 10]) # sonra esitligin karsi tarafindaki sayilari diger numpy dizisine aktariyoruz.

In [5]:
b

array([12, 10])

In [6]:
x = np.linalg.solve(a, b) # bu fonksiyonla da numpy kendi kendine cozuyor

In [7]:
x

array([1.85714286, 2.71428571])

In [11]:
import numpy as np

vector = np.random.randint(10, (3, 2))

np.transpose(vector) 

ValueError: low >= high