In [1]:
liste = [1, 2, 3, 4, 5]

In [2]:
for i in liste:
    print(i + 10)

11
12
13
14
15


In [3]:
list(map(lambda x: x + 10, liste)) # map, verilen bir nesne üzerinde tanımlanacak fonksiyonu çalıştırma imkanı verir. Listedeki her sayıyı değiştirmek için kullanılır

[11, 12, 13, 14, 15]

In [4]:
# filter

liste = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
list(filter(lambda x: x % 2 == 0, liste)) # Listedeki elemanları bir koşula göre filtreler. Listeden bazı sayıları seçmek için kullanılır
# map() ve filter() fonksiyonları sadece listelerle sınırlı değil. Herhangi bir "iterable" (yani üzerinde gezinilebilen) veri yapısıyla kullanılabilir

[2, 4, 6, 8, 10]

In [6]:
# reduce (indirgemek)

from functools import reduce

liste = [1, 2, 3, 4]
reduce(lambda a, b: a + b, liste)

# reduce() fonksiyonu listedeki tüm elemanları tek bir değere indirger

10

In [7]:
import pandas as pd 
import numpy as np 

my_dict = {'Alperen': 45, 'Emirhan': 50}
my_frame = pd.DataFrame(list(my_dict.items()), columns=["İsim", "Yaş"])
print(my_frame)

      İsim  Yaş
0  Alperen   45
1  Emirhan   50


In [8]:
import seaborn as sns 

flights = sns.load_dataset('diamonds')
df = flights.copy()
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0  326.0  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0  326.0  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0  327.0  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0  334.0  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0  335.0  4.34  4.35  2.75

In [9]:
arr = np.random.rand(3, 3)
arr

array([[0.46910529, 0.60325586, 0.36795671],
       [0.83700245, 0.76379019, 0.45436523],
       [0.19686129, 0.61125118, 0.06680811]])

In [10]:
arr

array([[0.46910529, 0.60325586, 0.36795671],
       [0.83700245, 0.76379019, 0.45436523],
       [0.19686129, 0.61125118, 0.06680811]])

In [11]:
arrr = np.random.randint(2, 56, 4) 
arrr 

array([ 6, 54, 41, 25], dtype=int32)

In [12]:
bek = np.array([23, 23, 'selam'])

In [13]:
bek

array(['23', '23', 'selam'], dtype='<U21')

In [14]:
df = df.dropna(axis=0)

In [15]:
X = df.drop(['price', 'cut', 'color', 'clarity'], axis=1)

In [16]:
y = df['price']

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=23)

In [ ]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import mean_squared_error
y_pred = logreg.predict(X_test)
np.sqrt(mean_squared_error)